### ISSUE TITLE
Path Setting for Imports

### ISSUE THREAD

**Issue by checkcode555** [crossecore/ecore-typescript#37]
Hi,

interesting project! I am building a node-based server with webpack. It seems like configurations mentioned in the referenced projects are not up to date, since there is no "lib" folder.

"paths": {
      "ecore/*": ["../node_modules/crossecore/lib/*"] // This mapping is relative to "baseUrl"
    },

Do you have any suggestions how to reference the library correctly so that imports work?

**Comment by schwichti** [comment]
I think it's now:

```json
"paths": {
"ecore/*": ["node_modules/crossecore/typings/*"] 
},
```
See https://github.com/crossecore/crossecore-generator/blob/referencing-packages/src/com/crossecore/typescript/TSConfigGenerator.xtend#L48.
At best you should generate your code using the `referencing-packages` branch of the generator.

**Comment by checkcode555** [comment]
Thanks, unfortunately the branch referencing-packages does not generate Jar file, even if it says that the build was successful. 
I see no errors to understand what went wrong. The Jar and the folders are not here: `build/libs/crossecore-generator_20200201-0643.jar` as it is mentioned in the README file. 

btw. I have no problems with the version from the master branch.

**Comment by schwichti** [comment]
Make sure that you call the `customFatJar` task:
```bash
./gradlew customFatJar
```
I tried it just now with a clean install from a fresh clone and the jar is created.

Alternatively, you can generate an Eclipse project with:
```bash
./gradlew eclipse
```
and then create a run configuration within Eclipse:
![grafik](https://user-images.githubusercontent.com/33393719/125683316-398a9b1b-34e6-441b-a5cb-e072be290c05.png)

**Comment by schwichti** [comment]
Also note that the semantics of the -p parameter has changed as it now creates a project layout with subfolders. One of these subfolders is `./src`, so you can remove it from the path you specify with -p parameter.

See: https://github.com/crossecore/crossecore-generator/issues/32 and https://github.com/crossecore/crossecore-generator/issues/34#issuecomment-832980042

**Comment by checkcode555** [comment]
Thanks for so many advices. I managed to build it, but I receive an error, when I try to use the Jar file. 

java -jar crossecore-generator.jar -L typescript -e Model.ecore -p ./output/mypackage/ - I use these three parameters too.

Exception in thread "main" java.util.MissingResourceException: The string resource '_UI_DiagnosticRoot_diagnostic' could not be located
        at org.eclipse.emf.common.util.DelegatingResourceLocator.delegatedGetString(DelegatingResourceLocator.java:541)
        at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:445)
        at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:560)
        at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:552)
        at org.eclipse.emf.ecore.util.Diagnostician.createDefaultDiagnostic(Diagnostician.java:110)
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:129)
        at com.crossecore.CrossEcore.main(CrossEcore.java:145)

**Comment by schwichti** [comment]
pull the last change https://github.com/crossecore/crossecore-generator/commit/82e73ab33402ae1c27a1793ecf4b8fc353bc4655 and try again

**Comment by checkcode555** [comment]
Thanks a lot! Now it functions without problems.
